github:
  issues: true
  workflows: true
  discussions: true
  dependabot: true
  pull_requests: true
  projects:
    enabled: true
    number: 6
registry:
  github: true
  dockerhub: true
security:
  scan: true
  signing: true
  sbom:
    enabled: false
    format: spdx
organization: broadsage
metadata:
  maintainer:
    name: Broadsage
    email: opensource@broadsage.com
  vendor: Broadsage Corporation Limited
  license: Apache-2.0
build:
  context: .
  dockerfile: Dockerfile.custom
  platforms:
  - linux/amd64
  cache:
    enabled: true
    type: gha
    mode: max
image:
  name: docker-scaffold
  description: Ansible-powered scaffolding tool for Docker image repositories
documentation:
  readme: true
  changelog: true
  contributing: true
  license: true
features:
  github: true
  security: true
  registry: true
