# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
---
# tasks file for roles/compliance

- name: Copy compliance files to project root (if not excluded)
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
    owner: "abc"
    group: "abc"
    mode: "0644"
  loop:
    - .conform.yaml
    - .mega-linter.yaml
    - publiccode.yml
    - REUSE.toml
  when: item not in template.exclude | default([])