# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
---
# tasks file for compliance
# Orchestrates both setup and cleanup tasks

- name: Include compliance setup tasks
  ansible.builtin.include_tasks: setup.yml

- name: Include compliance cleanup tasks
  ansible.builtin.include_tasks: cleanup.yml
