# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
---
# tasks file for documentation

- name: Create docs directory
  ansible.builtin.file:
    path: "/tmp/docs"
    state: directory
    mode: "0755"

- name: Copy documentation files to docs directory
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/tmp/docs/{{ item }}"
    mode: "0644"
  loop:
    - conform-guide.md
